// frontend2/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

interface QuickAction {
  title: string;
  description: string;
  icon: string;
  href: string;
  color: string;
}

interface Stat {
  label: string;
  value: string;
  icon: string;
  trend: string;
  bgColor: string;
}

interface Activity {
  action: string;
  time: string;
  icon: string;
}

interface SystemMetric {
  name: string;
  value: number;
  icon: string;
  color: string;
  gradientColor: string;
}

interface Particle {
  x: number;
  y: number;
  targetX: number;
  targetY: number;
  delay: number;
  type: string;
  vx: number;
  vy: number;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="relative min-h-screen bg-black overflow-hidden">
      <!-- Animated Particle Background -->
      <div class="absolute inset-0 particle-container">
        <!-- Floating particles -->
        <div class="particle" *ngFor="let particle of particles; trackBy: trackParticle" 
             [style.left.px]="particle.x" 
             [style.top.px]="particle.y"
             [style.animation-delay]="particle.delay + 's'"
             [ngClass]="particle.type"></div>
      </div>

      <!-- Main Content with Glass Effect -->
      <div class="relative z-10 min-h-screen p-8">
        
        <!-- Hero Section with Particle Text Effect -->
        <div class="relative text-center mb-16 pt-20">
          <div class="particle-text-container mb-8">
            <h1 class="text-6xl md:text-8xl font-thin tracking-wider text-transparent bg-clip-text bg-gradient-to-r from-white via-blue-200 to-green-200 animate-glow">
              DOBRODOŠLI
            </h1>
            <div class="text-2xl md:text-3xl font-light text-blue-200 mt-4 opacity-80 animate-fade-in">
              {{ currentUser.name }}
            </div>
          </div>
          <div class="cosmic-line"></div>
          <p class="text-lg text-gray-300 mt-8 max-w-2xl mx-auto font-light leading-relaxed">
            Vaš lični centar za upravljanje turističkim avanturama i destinacijama
          </p>
        </div>

        <!-- Quick Actions - Floating Glass Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-20">
          <div *ngFor="let action of quickActions; let i = index" 
               class="cosmic-card group cursor-pointer"
               [style.animation-delay]="(i * 0.2) + 's'">
            <div class="glass-panel p-8 text-center relative overflow-hidden">
              <!-- Particle trail effect -->
              <div class="particle-trail"></div>
              
              <div class="cosmic-icon mb-6 group-hover:scale-110 transition-all duration-500">
                <span class="text-5xl block cosmic-glow">{{ action.icon }}</span>
              </div>
              
              <h3 class="text-xl font-light text-white mb-3 tracking-wide">{{ action.title }}</h3>
              <p class="text-sm text-gray-400 font-light leading-relaxed">{{ action.description }}</p>
              
              <!-- Hover effect particles -->
              <div class="absolute inset-0 pointer-events-none">
                <div class="hover-particles opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
              </div>
            </div>
          </div>
        </div>

        <!-- Stats Section - Constellation Layout -->
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-20">
          
          <!-- Stats Constellation -->
          <div class="lg:col-span-2">
            <div class="glass-panel p-10 relative">
              <div class="flex items-center mb-8">
                <div class="cosmic-icon mr-4">
                  <span class="text-3xl cosmic-glow">📊</span>
                </div>
                <h2 class="text-2xl font-light text-white tracking-wide">Statistike Putovanja</h2>
              </div>
              
              <div class="grid grid-cols-1 md:grid-cols-2 gap-10">
                <div *ngFor="let stat of stats; let i = index" 
                     class="stat-constellation"
                     [style.animation-delay]="(i * 0.3) + 's'">
                  <div class="flex items-center space-x-6">
                    <div class="cosmic-icon-large">
                      <span class="text-4xl cosmic-glow">{{ stat.icon }}</span>
                    </div>
                    <div>
                      <div class="text-4xl font-thin text-white mb-1 cosmic-number">{{ stat.value }}</div>
                      <div class="text-lg text-gray-300 font-light">{{ stat.label }}</div>
                      <div class="text-sm text-blue-300 mt-2 font-light cosmic-trend">{{ stat.trend }}</div>
                    </div>
                  </div>
                  <!-- Connecting line particles -->
                  <div class="constellation-line"></div>
                </div>
              </div>
            </div>
          </div>

          <!-- Activity Stream -->
          <div>
            <div class="glass-panel p-10 relative">
              <div class="flex items-center mb-8">
                <div class="cosmic-icon mr-4">
                  <span class="text-3xl cosmic-glow">�</span>
                </div>
                <h2 class="text-2xl font-light text-white tracking-wide">Nedavna Aktivnost</h2>
              </div>
              
              <div class="space-y-6">
                <div *ngFor="let activity of recentActivity; let i = index" 
                     class="activity-particle"
                     [style.animation-delay]="(i * 0.4) + 's'">
                  <div class="flex items-center space-x-4">
                    <div class="w-4 h-4 rounded-full bg-gradient-to-r from-blue-400 to-green-400 cosmic-pulse"></div>
                    <div class="flex-1">
                      <div class="text-white font-light">{{ activity.action }}</div>
                      <div class="text-gray-400 text-sm font-light">pre {{ activity.time }}</div>
                    </div>
                  </div>
                  <!-- Activity trail -->
                  <div class="activity-trail"></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- System Monitoring - Cosmic Grid -->
        <div class="glass-panel p-10 relative">
          <div class="flex items-center mb-8">
            <div class="cosmic-icon mr-4">
              <span class="text-3xl cosmic-glow">💻</span>
            </div>
            <h2 class="text-2xl font-light text-white tracking-wide">Sistemsko Praćenje</h2>
          </div>
          
          <div class="grid grid-cols-1 md:grid-cols-3 gap-10">
            <div *ngFor="let metric of systemMetrics; let i = index" 
                 class="metric-constellation"
                 [style.animation-delay]="(i * 0.2) + 's'">
              <div class="text-center">
                <div class="cosmic-icon-large mb-6">
                  <span class="text-5xl cosmic-glow">{{ metric.icon }}</span>
                </div>
                <div class="text-lg text-gray-300 mb-4 font-light">{{ metric.name }}</div>
                
                <!-- Cosmic Progress Ring -->
                <div class="relative w-24 h-24 mx-auto mb-4">
                  <svg class="w-24 h-24 transform -rotate-90" viewBox="0 0 100 100">
                    <!-- Background ring -->
                    <circle cx="50" cy="50" r="40" stroke="rgba(55, 65, 81, 0.3)" 
                            stroke-width="8" fill="none"/>
                    <!-- Progress ring -->
                    <circle cx="50" cy="50" r="40" 
                            stroke="url(#cosmicGradient)" 
                            stroke-width="8" 
                            fill="none"
                            stroke-linecap="round"
                            [style.stroke-dasharray]="251.2"
                            [style.stroke-dashoffset]="251.2 - (251.2 * metric.value / 100)"
                            class="cosmic-progress"/>
                    <defs>
                      <linearGradient id="cosmicGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" style="stop-color:#60A5FA"/>
                        <stop offset="50%" style="stop-color:#34D399"/>
                        <stop offset="100%" style="stop-color:#A78BFA"/>
                      </linearGradient>
                    </defs>
                  </svg>
                  <!-- Percentage in center -->
                  <div class="absolute inset-0 flex items-center justify-center">
                    <span class="text-2xl font-thin text-white cosmic-number">{{ metric.value }}%</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .particle-container {
      pointer-events: none;
    }
    
    .particle {
      position: absolute;
      width: 2px;
      height: 2px;
      border-radius: 50%;
      opacity: 0.7;
    }
    
    .particle.type-1 {
      background: radial-gradient(circle, rgba(96, 165, 250, 0.8) 0%, transparent 70%);
      animation: float1 8s infinite ease-in-out;
    }
    
    .particle.type-2 {
      background: radial-gradient(circle, rgba(52, 211, 153, 0.6) 0%, transparent 70%);
      animation: float2 12s infinite ease-in-out;
    }
    
    .particle.type-3 {
      background: radial-gradient(circle, rgba(167, 139, 250, 0.5) 0%, transparent 70%);
      animation: float3 10s infinite ease-in-out;
    }
    
    @keyframes float1 {
      0%, 100% { transform: translate(0, 0) scale(1); opacity: 0.7; }
      25% { transform: translate(100px, -50px) scale(1.2); opacity: 1; }
      50% { transform: translate(-50px, -100px) scale(0.8); opacity: 0.5; }
      75% { transform: translate(-80px, 50px) scale(1.1); opacity: 0.8; }
    }
    
    @keyframes float2 {
      0%, 100% { transform: translate(0, 0) rotate(0deg); opacity: 0.6; }
      33% { transform: translate(-120px, -80px) rotate(120deg); opacity: 1; }
      66% { transform: translate(80px, -60px) rotate(240deg); opacity: 0.4; }
    }
    
    @keyframes float3 {
      0%, 100% { transform: translate(0, 0) scale(1) rotate(0deg); opacity: 0.5; }
      50% { transform: translate(60px, -120px) scale(1.5) rotate(180deg); opacity: 1; }
    }
    
    .glass-panel {
      background: rgba(15, 23, 42, 0.4);
      backdrop-filter: blur(20px);
      border: 1px solid rgba(148, 163, 184, 0.1);
      border-radius: 20px;
      box-shadow: 
        0 0 40px rgba(96, 165, 250, 0.1),
        inset 0 1px 0 rgba(255, 255, 255, 0.1);
    }
    
    .cosmic-card {
      animation: cosmicRise 1s ease-out forwards;
      opacity: 0;
      transform: translateY(50px);
    }
    
    @keyframes cosmicRise {
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
    
    .cosmic-icon {
      position: relative;
    }
    
    .cosmic-icon-large {
      position: relative;
    }
    
    .cosmic-glow {
      filter: drop-shadow(0 0 10px rgba(96, 165, 250, 0.5));
      animation: iconGlow 3s ease-in-out infinite alternate;
    }
    
    @keyframes iconGlow {
      from { filter: drop-shadow(0 0 10px rgba(96, 165, 250, 0.5)); }
      to { filter: drop-shadow(0 0 20px rgba(52, 211, 153, 0.7)); }
    }
    
    .cosmic-line {
      width: 200px;
      height: 1px;
      background: linear-gradient(90deg, transparent, rgba(96, 165, 250, 0.5), rgba(52, 211, 153, 0.5), transparent);
      margin: 0 auto;
      animation: lineGlow 2s ease-in-out infinite alternate;
    }
    
    @keyframes lineGlow {
      from { box-shadow: 0 0 5px rgba(96, 165, 250, 0.3); }
      to { box-shadow: 0 0 15px rgba(52, 211, 153, 0.6); }
    }
    
    .animate-glow {
      animation: textGlow 4s ease-in-out infinite alternate;
    }
    
    @keyframes textGlow {
      from { 
        text-shadow: 0 0 20px rgba(96, 165, 250, 0.5);
        filter: brightness(1);
      }
      to { 
        text-shadow: 0 0 40px rgba(52, 211, 153, 0.8);
        filter: brightness(1.2);
      }
    }
    
    .animate-fade-in {
      animation: fadeIn 2s ease-out 0.5s both;
    }
    
    @keyframes fadeIn {
      from { opacity: 0; transform: translateY(20px); }
      to { opacity: 1; transform: translateY(0); }
    }
    
    .cosmic-pulse {
      animation: pulse 2s ease-in-out infinite;
    }
    
    @keyframes pulse {
      0%, 100% { 
        box-shadow: 0 0 0 0 rgba(96, 165, 250, 0.7);
        transform: scale(1);
      }
      50% { 
        box-shadow: 0 0 0 10px rgba(96, 165, 250, 0);
        transform: scale(1.1);
      }
    }
    
    .stat-constellation,
    .activity-particle,
    .metric-constellation {
      animation: cosmicFadeIn 1s ease-out forwards;
      opacity: 0;
      transform: translateX(-30px);
    }
    
    @keyframes cosmicFadeIn {
      to {
        opacity: 1;
        transform: translateX(0);
      }
    }
    
    .cosmic-number {
      animation: numberGlow 3s ease-in-out infinite alternate;
    }
    
    @keyframes numberGlow {
      from { color: rgba(255, 255, 255, 0.9); }
      to { color: rgba(96, 165, 250, 1); }
    }
    
    .cosmic-trend {
      animation: trendPulse 2s ease-in-out infinite;
    }
    
    @keyframes trendPulse {
      0%, 100% { opacity: 0.8; }
      50% { opacity: 1; }
    }
    
    .cosmic-progress {
      animation: progressGlow 3s ease-in-out infinite alternate;
      transition: stroke-dashoffset 1s ease-out;
    }
    
    @keyframes progressGlow {
      from { filter: drop-shadow(0 0 5px rgba(96, 165, 250, 0.5)); }
      to { filter: drop-shadow(0 0 15px rgba(52, 211, 153, 0.8)); }
    }
    
    .particle-trail {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      opacity: 0;
      background: radial-gradient(circle at center, rgba(96, 165, 250, 0.1) 0%, transparent 50%);
      animation: trailPulse 4s ease-in-out infinite;
    }
    
    @keyframes trailPulse {
      0%, 100% { opacity: 0; transform: scale(0.8); }
      50% { opacity: 1; transform: scale(1.2); }
    }
    
    .hover-particles {
      background: radial-gradient(circle, rgba(52, 211, 153, 0.2) 0%, transparent 70%);
      animation: hoverParticles 2s ease-in-out infinite;
    }
    
    @keyframes hoverParticles {
      0%, 100% { transform: scale(1) rotate(0deg); }
      50% { transform: scale(1.1) rotate(180deg); }
    }
    
    .activity-trail {
      position: absolute;
      left: 8px;
      top: 20px;
      width: 1px;
      height: calc(100% - 20px);
      background: linear-gradient(to bottom, rgba(96, 165, 250, 0.5), transparent);
      animation: trailFlow 3s ease-in-out infinite;
    }
    
    @keyframes trailFlow {
      0%, 100% { opacity: 0.3; }
      50% { opacity: 0.8; }
    }
    
    .constellation-line {
      position: absolute;
      right: -20px;
      top: 50%;
      width: 40px;
      height: 1px;
      background: linear-gradient(90deg, rgba(96, 165, 250, 0.3), transparent);
      animation: constellationPulse 2s ease-in-out infinite;
    }
    
    @keyframes constellationPulse {
      0%, 100% { opacity: 0.3; width: 40px; }
      50% { opacity: 0.8; width: 60px; }
    }
    
    /* Responsive font sizing */
    @media (max-width: 768px) {
      .text-6xl { font-size: 3rem; }
      .text-8xl { font-size: 4rem; }
    }
  `]
})
export class DashboardComponent implements OnInit {
  currentUser = {
    name: 'John Doe',
    role: 'vodič'
  };

  particles: Particle[] = [];
  mouseX: number = 0;
  mouseY: number = 0;

  quickActions: QuickAction[] = [
    {
      title: 'Kreiraj Turu',
      description: 'Napravite novu turističku rutu',
      icon: '�️',
      href: '/tours/create',
      color: 'bg-gradient-to-br from-blue-400 to-cyan-400'
    },
    {
      title: 'Napiš Blog',
      description: 'Podelite putna iskustva',
      icon: '✍️',
      href: '/blog/create',
      color: 'bg-gradient-to-br from-purple-400 to-blue-400'
    },
    {
      title: 'Istražite Destinacije',
      description: 'Otkrijte nova mesta',
      icon: '�',
      href: '/tours',
      color: 'bg-gradient-to-br from-green-400 to-blue-400'
    },
    {
      title: 'Zajednica',
      description: 'Povežite se sa putnicima',
      icon: '�',
      href: '/followers',
      color: 'bg-gradient-to-br from-pink-400 to-purple-400'
    }
  ];

  stats: Stat[] = [
    { label: 'Aktivne Ture', value: '12', icon: '�️', trend: '+2 ova nedelja', bgColor: 'from-blue-400 to-cyan-400' },
    { label: 'Objavljeni Blogovi', value: '5', icon: '✍️', trend: '+1 danas', bgColor: 'from-purple-400 to-blue-400' },
    { label: 'Pratilaca', value: '248', icon: '�', trend: '+15 ova nedelja', bgColor: 'from-green-400 to-blue-400' },
    { label: 'Ukupno Pregleda', value: '1,234', icon: '👁️', trend: '+89 danas', bgColor: 'from-pink-400 to-purple-400' }
  ];

  recentActivity: Activity[] = [
    { action: 'Nova destinacija dodana', time: '2 sata', icon: '�' },
    { action: 'Blog o Parizu objavljen', time: '5 sati', icon: '✍️' },
    { action: 'Novi pratilac se pridružio', time: '1 dan', icon: '�' },
    { action: 'Tura u Rimu završena', time: '2 dana', icon: '�️' }
  ];

  systemMetrics: SystemMetric[] = [
    { name: 'Performanse Servera', value: 65, icon: '🖥️', color: 'text-blue-400', gradientColor: 'from-blue-400 to-cyan-500' },
    { name: 'Memorija', value: 78, icon: '�', color: 'text-purple-400', gradientColor: 'from-purple-400 to-pink-500' },
    { name: 'Disk Prostor', value: 45, icon: '💿', color: 'text-green-400', gradientColor: 'from-green-400 to-blue-500' }
  ];

  ngOnInit() {
    this.generateParticles();
    this.setupMouseListener();
    this.animateParticles();
  }

  generateParticles() {
    const particleCount = 150;
    this.particles = [];
    
    // Check if running in browser environment
    const screenWidth = typeof window !== 'undefined' ? window.innerWidth : 1920;
    const screenHeight = typeof window !== 'undefined' ? window.innerHeight : 1080;
    
    for (let i = 0; i < particleCount; i++) {
      const x = Math.random() * screenWidth;
      const y = Math.random() * screenHeight;
      this.particles.push({
        x: x,
        y: y,
        targetX: x,
        targetY: y,
        delay: Math.random() * 10,
        type: `type-${Math.floor(Math.random() * 3) + 1}`,
        vx: 0,
        vy: 0
      });
    }
  }

  setupMouseListener() {
    if (typeof window !== 'undefined') {
      window.addEventListener('mousemove', (e) => {
        this.mouseX = e.clientX;
        this.mouseY = e.clientY;
        this.updateParticleTargets();
      });
    }
  }

  updateParticleTargets() {
    this.particles.forEach(particle => {
      const dx = this.mouseX - particle.x;
      const dy = this.mouseY - particle.y;
      const distance = Math.sqrt(dx * dx + dy * dy);
      
      if (distance < 150) {
        // Repel particles from mouse
        const force = (150 - distance) / 150;
        particle.targetX = particle.x - (dx / distance) * force * 50;
        particle.targetY = particle.y - (dy / distance) * force * 50;
      } else {
        // Return to original position
        particle.targetX = particle.x;
        particle.targetY = particle.y;
      }
    });
  }

  animateParticles() {
    if (typeof window !== 'undefined') {
      const animate = () => {
        this.particles.forEach(particle => {
          // Smooth movement towards target
          const dx = particle.targetX - particle.x;
          const dy = particle.targetY - particle.y;
          
          particle.vx += dx * 0.01;
          particle.vy += dy * 0.01;
          
          // Add some damping
          particle.vx *= 0.95;
          particle.vy *= 0.95;
          
          particle.x += particle.vx;
          particle.y += particle.vy;
        });
        
        requestAnimationFrame(animate);
      };
      animate();
    }
  }

  trackParticle(index: number, particle: Particle): number {
    return index;
  }
}

// frontend2/src/__react_backup__/pages/Dashboard.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  MapPin,
  Compass,
  BookOpen,
  Users,
  TrendingUp,
  Clock,
  Star,
  ShoppingCart,
  Activity,
  Cpu,
  HardDrive,
} from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { Link } from 'react-router-dom';

const Dashboard = () => {
  const { user } = useAuth();

  const quickActions = [
    {
      title: 'Kreiraj Turu',
      description: 'Napravite novu turu sa ključnim tačkama',
      icon: MapPin,
      href: '/tours/create',
      color: 'bg-gradient-primary',
      condition: user?.role === 'vodič' || user?.role === 'admin',
    },
    {
      title: 'Napiši Blog',
      description: 'Podelite svoja iskustva',
      icon: BookOpen,
      href: '/blog/create',
      color: 'bg-gradient-secondary',
    },
    {
      title: 'Istražite Ture',
      description: 'Otkrijte nove destinacije',
      icon: Compass,
      href: '/tours',
      color: 'bg-gradient-accent',
    },
    {
      title: 'Zajednica',
      description: 'Povežite se sa drugim putnicima',
      icon: Users,
      href: '/followers',
      color: 'bg-gradient-primary',
    },
  ].filter(action => action.condition !== false);

  const stats = [
    { label: 'Aktivne Ture', value: '12', icon: MapPin, trend: '+2 ova nedelja' },
    { label: 'Blog Postovi', value: '5', icon: BookOpen, trend: '+1 danas' },
    { label: 'Pratioci', value: '248', icon: Users, trend: '+15 ova nedelja' },
    { label: 'Ukupno Poena', value: '1,234', icon: Star, trend: '+89 danas' },
  ];

  const recentActivity = [
    { action: 'Nova tura kreirana', time: '2 sata', icon: MapPin },
    { action: 'Blog post objavljen', time: '5 sati', icon: BookOpen },
    { action: 'Novi pratilac', time: '1 dan', icon: Users },
    { action: 'Recenzija dobila', time: '2 dana', icon: Star },
  ];

  const systemMetrics = [
    { name: 'CPU Korišćenje', value: 65, icon: Cpu, color: 'text-primary' },
    { name: 'RAM Memorija', value: 78, icon: HardDrive, color: 'text-secondary' },
    { name: 'Disk Prostor', value: 45, icon: Activity, color: 'text-accent' },
  ];

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      {/* Welcome Section */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mb-8"
      >
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-3xl font-bold mb-2">
              Dobrodošli, {user?.username}!
            </h1>
            <p className="text-muted-foreground">
              Evo pregleda vaše aktivnosti i brzih akcija
            </p>
          </div>
          <Badge 
            variant="secondary" 
            className="px-3 py-1 text-sm font-medium capitalize bg-gradient-primary text-primary-foreground"
          >
            {user?.role}
          </Badge>
        </div>
      </motion.div>

      {/* Quick Actions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="mb-8"
      >
        <h2 className="text-xl font-semibold mb-4">Brze Akcije</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {quickActions.map((action, index) => (
            <motion.div
              key={action.title}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <Link to={action.href}>
                <Card className="glass-card hover:shadow-hover transition-all duration-300 h-full">
                  <CardContent className="p-6">
                    <div className={`w-12 h-12 rounded-lg ${action.color} flex items-center justify-center mb-4`}>
                      <action.icon className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="font-semibold mb-2">{action.title}</h3>
                    <p className="text-sm text-muted-foreground">{action.description}</p>
                  </CardContent>
                </Card>
              </Link>
            </motion.div>
          ))}
        </div>
      </motion.div>

      <div className="grid lg:grid-cols-3 gap-8">
        {/* Stats Overview */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="lg:col-span-2"
        >
          <Card className="glass-card">
            <CardHeader>
              <CardTitle className="flex items-center space-x-2">
                <TrendingUp className="w-5 h-5" />
                <span>Statistike</span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {stats.map((stat, index) => (
                  <motion.div
                    key={stat.label}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: index * 0.1 }}
                    className="flex items-center space-x-4"
                  >
                    <div className="w-12 h-12 bg-gradient-primary rounded-lg flex items-center justify-center">
                      <stat.icon className="w-6 h-6 text-primary-foreground" />
                    </div>
                    <div>
                      <div className="text-2xl font-bold">{stat.value}</div>
                      <div className="text-sm text-muted-foreground">{stat.label}</div>
                      <div className="text-xs text-success">{stat.trend}</div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Recent Activity */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <Card className="glass-card">
            <CardHeader>
              <CardTitle className="flex items-center space-x-2">
                <Clock className="w-5 h-5" />
                <span>Poslednja Aktivnost</span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {recentActivity.map((activity, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.3, delay: index * 0.1 }}
                    className="flex items-center space-x-3"
                  >
                    <div className="w-8 h-8 bg-muted rounded-full flex items-center justify-center">
                      <activity.icon className="w-4 h-4" />
                    </div>
                    <div className="flex-1">
                      <div className="text-sm">{activity.action}</div>
                      <div className="text-xs text-muted-foreground">pre {activity.time}</div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>

      {/* System Monitoring - Demo */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.4 }}
        className="mt-8"
      >
        <Card className="glass-card">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Activity className="w-5 h-5" />
              <span>Sistemsko Praćenje (Demo)</span>
            </CardTitle>
            <CardDescription>
              Pregled performansi servera i kontejnera
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {systemMetrics.map((metric, index) => (
                <motion.div
                  key={metric.name}
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ duration: 0.3, delay: index * 0.1 }}
                  className="flex items-center space-x-4"
                >
                  <metric.icon className={`w-8 h-8 ${metric.color}`} />
                  <div className="flex-1">
                    <div className="flex justify-between items-center mb-1">
                      <span className="text-sm font-medium">{metric.name}</span>
                      <span className="text-sm text-muted-foreground">{metric.value}%</span>
                    </div>
                    <div className="w-full bg-muted rounded-full h-2">
                      <motion.div
                        className="h-2 rounded-full bg-gradient-primary"
                        initial={{ width: 0 }}
                        animate={{ width: `${metric.value}%` }}
                        transition={{ duration: 1, delay: index * 0.2 }}
                      />
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
};

export default Dashboard;
