// frontend2/src/__react_backup__/components/ParticleSystem.tsx
import React, { useEffect, useRef } from 'react';

interface Particle {
  id: number;
  x: number;
  y: number;
  size: number;
  speedX: number;
  speedY: number;
  opacity: number;
  life: number;
}

const ParticleSystem: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const particlesRef = useRef<Particle[]>([]);
  const animationRef = useRef<number>();

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Set canvas size
    const updateCanvasSize = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    };

    updateCanvasSize();
    window.addEventListener('resize', updateCanvasSize);

    // Create initial particles
    const createParticle = (): Particle => ({
      id: Math.random(),
      x: Math.random() * canvas.width,
      y: canvas.height + 10,
      size: Math.random() * 3 + 1,
      speedX: (Math.random() - 0.5) * 2,
      speedY: -(Math.random() * 3 + 2),
      opacity: Math.random() * 0.8 + 0.2,
      life: 1,
    });

    // Initialize particles
    for (let i = 0; i < 50; i++) {
      particlesRef.current.push(createParticle());
    }

    const animate = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);

      // Update and draw particles
      particlesRef.current.forEach((particle, index) => {
        // Update position
        particle.x += particle.speedX;
        particle.y += particle.speedY;

        // Update life
        particle.life -= 0.01;

        // Remove dead particles
        if (particle.life <= 0 || particle.y < -10) {
          particlesRef.current[index] = createParticle();
        }

        // Draw particle
        ctx.save();
        ctx.globalAlpha = particle.opacity * particle.life;
        ctx.fillStyle = '#ffffff';
        ctx.beginPath();
        ctx.arc(particle.x, particle.y, particle.size, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
      });

      // Occasionally add new particles
      if (Math.random() < 0.3 && particlesRef.current.length < 80) {
        particlesRef.current.push(createParticle());
      }

      animationRef.current = requestAnimationFrame(animate);
    };

    animate();

    return () => {
      window.removeEventListener('resize', updateCanvasSize);
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
    };
  }, []);

  return (
    <canvas
      ref={canvasRef}
      className="fixed inset-0 pointer-events-none z-0"
      style={{ mixBlendMode: 'screen' }}
    />
  );
};

export default ParticleSystem;

// frontend2/src/app/shared/components/layout/particle-system.component.ts
import { Component, ElementRef, OnInit, OnDestroy, ViewChild, Inject, PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { CommonModule } from '@angular/common';

interface Particle {
  id: number;
  x: number;
  y: number;
  size: number;
  speedX: number;
  speedY: number;
  opacity: number;
  life: number;
}

@Component({
  selector: 'app-particle-system',
  standalone: true,
  imports: [CommonModule],
  template: `
    <canvas
      *ngIf="isBrowser"
      #canvas
      class="fixed inset-0 pointer-events-none z-0"
      [ngStyle]="{ 'mix-blend-mode': 'screen' }"
    ></canvas>
  `,
  styles: []
})
export class ParticleSystemComponent implements OnInit, OnDestroy {
  @ViewChild('canvas', { static: true }) canvasRef?: ElementRef<HTMLCanvasElement>;
  
  private particles: Particle[] = [];
  private animationId?: number;
  private ctx?: CanvasRenderingContext2D;

  public isBrowser: boolean;

  constructor(@Inject(PLATFORM_ID) private platformId: Object) {
    this.isBrowser = isPlatformBrowser(this.platformId);
  }

  ngOnInit(): void {
    if (this.isBrowser && this.canvasRef && this.canvasRef.nativeElement) {
      this.initializeParticleSystem();
    }
  }

  ngOnDestroy(): void {
    if (!this.isBrowser) return;
    if (this.animationId) {
      cancelAnimationFrame(this.animationId);
    }
    if (typeof window !== 'undefined') {
      window.removeEventListener('resize', this.updateCanvasSize);
    }
  }

  private initializeParticleSystem(): void {
    if (!this.isBrowser || !this.canvasRef || !this.canvasRef.nativeElement) return;
    const canvas = this.canvasRef.nativeElement;
    this.ctx = canvas.getContext('2d')!;

    this.updateCanvasSize();
    window.addEventListener('resize', this.updateCanvasSize.bind(this));

    // Create initial particles
    for (let i = 0; i < 50; i++) {
      this.particles.push(this.createParticle());
    }

    this.animate();
  }

  private updateCanvasSize = (): void => {
    if (!this.isBrowser || !this.canvasRef || !this.canvasRef.nativeElement) return;
    const canvas = this.canvasRef.nativeElement;
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
  };

  private createParticle(): Particle {
    const width = this.canvasRef && this.canvasRef.nativeElement ? this.canvasRef.nativeElement.width : 0;
    const height = this.canvasRef && this.canvasRef.nativeElement ? this.canvasRef.nativeElement.height : 0;
    return {
      id: Math.random(),
      x: Math.random() * width,
      y: height + 10,
      size: Math.random() * 3 + 1,
      speedX: (Math.random() - 0.5) * 2,
      speedY: -(Math.random() * 3 + 2),
      opacity: Math.random() * 0.8 + 0.2,
      life: 1,
    };
  }

  private animate = (): void => {
    if (!this.isBrowser || !this.ctx || !this.canvasRef || !this.canvasRef.nativeElement) return;

    const canvas = this.canvasRef.nativeElement;
    this.ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Update and draw particles
    this.particles.forEach((particle, index) => {
      // Update position
      particle.x += particle.speedX;
      particle.y += particle.speedY;

      // Update life
      particle.life -= 0.01;

      // Remove dead particles
      if (particle.life <= 0 || particle.y < -10) {
        this.particles[index] = this.createParticle();
      }

      // Draw particle
      this.ctx!.save();
      this.ctx!.globalAlpha = particle.opacity * particle.life;
      this.ctx!.fillStyle = '#ffffff';
      this.ctx!.beginPath();
      this.ctx!.arc(particle.x, particle.y, particle.size, 0, Math.PI * 2);
      this.ctx!.fill();
      this.ctx!.restore();
    });

    // Occasionally add new particles
    if (Math.random() < 0.3 && this.particles.length < 80) {
      this.particles.push(this.createParticle());
    }

    this.animationId = requestAnimationFrame(this.animate);
  };
}
